In [1]:
import pandas as pd

companies = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\companies.xlsx",
    header=1
)

master_ids = set(companies["id"])
print(master_ids)
print(len(master_ids),"unique ids in companies.xlsx")

pl_ids = set(
    pd.read_excel(
        r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\profitandloss.xlsx",
        header=1
    )["company_id"]
)
print("\n",pl_ids)
print(len(pl_ids),"unique ids in profitandloss.xlsx")

# Find IDs in pl_ids that are not in master_ids
extras = sorted(pl_ids - master_ids)

# Show the list
print("\n", extras)

# Show how many extras there are
print(len(extras), "extra ids that are not in companies.xlsx")

{'PIDILITIND', 'DIVISLAB', 'JIOFIN', 'ADANIPORTS', 'CANBK', 'LTIM', 'HAVELLS', 'PFC', 'DMART', 'TATAPOWER', 'JINDALSTEL', 'APOLLOHOSP', 'BAJAJ-AUTO', 'BHEL', 'TATASTEEL', 'DLF', 'ONGC', 'ADANIPOWER', 'AXISBANK', 'JSWENERGY', 'PNB', 'SHREECEM', 'LT', 'DRREDDY', 'TRENT', 'JSWSTEEL', 'RELIANCE', 'TVSMOTOR', 'BAJAJHLDNG', 'RECLTD', 'ICICIPRULI', 'HINDUNILVR', 'SUNPHARMA', 'ADANIGREEN', 'ASIANPAINT', 'ITC', 'SBIN', 'LICI', 'MOTHERSON', 'BPCL', 'IRFC', 'NAUKRI', 'NESTLEIND', 'TECHM', 'BANKBARODA', 'TORNTPHARM', 'IRCTC', 'M&M', 'LODHA', 'ADANIENSOL', 'HAL', 'ATGL', 'ICICIBANK', 'SHRIRAMFIN', 'AMBUJACEM', 'IOC', 'KOTAKBANK', 'GAIL', 'HCLTECH', 'BOSCHLTD', 'TATAMOTORS', 'CHOLAFIN', 'EICHERMOT', 'BRITANNIA', 'INDUSINDBK', 'BEL', 'ADANIENT', 'SIEMENS', 'GRASIM', 'BAJAJFINSV', 'TCS', 'CIPLA', 'POWERGRID', 'TATACONSUM', 'DABUR', 'COALINDIA', 'BHARTIARTL', 'HDFCLIFE', 'NTPC', 'BAJFINANCE', 'INFY', 'HINDALCO', 'HDFCBANK', 'MARUTI', 'ICICIGI', 'INDIGO', 'GODREJCP', 'TITAN', 'SBILIFE', 'ABB', 'NHPC', 'HEROMOTOCO'}
92 unique ids in companies.xlsx

 {'PIDILITIND', 'UNITDSPR', 'DIVISLAB', 'JIOFIN', 'ADANIPORTS', 'CANBK', 'LTIM', 'HAVELLS', 'PFC', 'DMART', 'TATAPOWER', 'JINDALSTEL', 'APOLLOHOSP', 'BAJAJ-AUTO', 'BHEL', 'TATASTEEL', 'DLF', 'ONGC', 'ADANIPOWER', 'AXISBANK', 'JSWENERGY', 'PNB', 'SHREECEM', 'LT', 'DRREDDY', 'TRENT', 'JSWSTEEL', 'RELIANCE', 'TVSMOTOR', 'BAJAJHLDNG', 'RECLTD', 'ICICIPRULI', 'HINDUNILVR', 'SUNPHARMA', 'ADANIGREEN', 'ASIANPAINT', 'ITC', 'SBIN', 'LICI', 'MOTHERSON', 'VEDL', 'BPCL', 'IRFC', 'NAUKRI', 'NESTLEIND', 'TECHM', 'BANKBARODA', 'TORNTPHARM', 'ZOMATO', 'IRCTC', 'M&M', 'LODHA', 'ADANIENSOL', 'HAL', 'ATGL', 'WIPRO', 'ICICIBANK', 'SHRIRAMFIN', 'AMBUJACEM', 'IOC', 'KOTAKBANK', 'GAIL', 'HCLTECH', 'BOSCHLTD', 'TATAMOTORS', 'CHOLAFIN', 'EICHERMOT', 'BRITANNIA', 'INDUSINDBK', 'BEL', 'ADANIENT', 'ULTRACEMCO', 'SIEMENS', 'GRASIM', 'BAJAJFINSV', 'TCS', 'CIPLA', 'POWERGRID', 'TATACONSUM', 'DABUR', 'COALINDIA', 'BHARTIARTL', 'HDFCLIFE', 'NTPC', 'BAJFINANCE', 'INFY', 'HINDALCO', 'HDFCBANK', 'ZYDUSLIFE', 'MARUTI', 'ICICIGI', 'UNIONBANK', 'INDIGO', 'GODREJCP', 'TITAN', 'SBILIFE', 'ABB', 'NHPC', 'HEROMOTOCO', 'VBL'}
100 unique ids in profitandloss.xlsx

 ['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']
8 extra ids that are not in companies.xlsx

In [13]:
import pandas as pd

companies = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\companies.xlsx",
    header=1
)

master_ids = set(companies["id"])
print(master_ids)
print(len(master_ids))

pl_ids = set(
    pd.read_excel(
        r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\balancesheet.xlsx",
        header=1
    )["company_id"]
)
print("\n",pl_ids)
print(len(pl_ids))

print("\n",sorted(pl_ids - master_ids))

{'HAL', 'SHRIRAMFIN', 'ICICIPRULI', 'GODREJCP', 'PFC', 'NESTLEIND', 'PNB', 'TATASTEEL', 'JSWENERGY', 'ADANIPORTS', 'DABUR', 'LT', 'ADANIENSOL', 'APOLLOHOSP', 'HDFCLIFE', 'GAIL', 'BPCL', 'AMBUJACEM', 'AXISBANK', 'CIPLA', 'ICICIBANK', 'CANBK', 'LTIM', 'BHEL', 'IRCTC', 'TECHM', 'M&M', 'BHARTIARTL', 'IRFC', 'ADANIGREEN', 'CHOLAFIN', 'MARUTI', 'TORNTPHARM', 'JIOFIN', 'TATACONSUM', 'ATGL', 'ADANIPOWER', 'SBIN', 'DMART', 'TRENT', 'TITAN', 'SBILIFE', 'ASIANPAINT', 'BAJAJFINSV', 'HAVELLS', 'ITC', 'ONGC', 'ICICIGI', 'DLF', 'LICI', 'HCLTECH', 'DIVISLAB', 'MOTHERSON', 'NAUKRI', 'NTPC', 'COALINDIA', 'HINDUNILVR', 'EICHERMOT', 'ADANIENT', 'BANKBARODA', 'IOC', 'TATAPOWER', 'BRITANNIA', 'JSWSTEEL', 'TCS', 'RELIANCE', 'TATAMOTORS', 'BOSCHLTD', 'PIDILITIND', 'HINDALCO', 'INDUSINDBK', 'INDIGO', 'ABB', 'LODHA', 'SHREECEM', 'NHPC', 'BAJAJ-AUTO', 'BAJFINANCE', 'RECLTD', 'HDFCBANK', 'DRREDDY', 'POWERGRID', 'GRASIM', 'KOTAKBANK', 'TVSMOTOR', 'HEROMOTOCO', 'JINDALSTEL', 'INFY', 'BAJAJHLDNG', 'SIEMENS', 'BEL', 'SUNPHARMA'}
92

 {'HAL', 'SHRIRAMFIN', 'ICICIPRULI', 'GODREJCP', 'PFC', 'NESTLEIND', 'PNB', 'TATASTEEL', 'JSWENERGY', 'ADANIPORTS', 'DABUR', 'LT', 'ADANIENSOL', 'UNITDSPR', 'ZYDUSLIFE', 'APOLLOHOSP', 'HDFCLIFE', 'GAIL', 'BPCL', 'AMBUJACEM', 'AXISBANK', 'CIPLA', 'ICICIBANK', 'CANBK', 'LTIM', 'BHEL', 'IRCTC', 'TECHM', 'M&M', 'BHARTIARTL', 'IRFC', 'ADANIGREEN', 'CHOLAFIN', 'MARUTI', 'TORNTPHARM', 'JIOFIN', 'TATACONSUM', 'ATGL', 'ADANIPOWER', 'DMART', 'TRENT', 'UNIONBANK', 'TITAN', 'SBILIFE', 'ASIANPAINT', 'BAJAJFINSV', 'HAVELLS', 'ITC', 'ONGC', 'ICICIGI', 'DLF', 'LICI', 'HCLTECH', 'DIVISLAB', 'VEDL', 'MOTHERSON', 'NAUKRI', 'NTPC', 'COALINDIA', 'HINDUNILVR', 'EICHERMOT', 'ADANIENT', 'BANKBARODA', 'IOC', 'TATAPOWER', 'WIPRO', 'BRITANNIA', 'ULTRACEMCO', 'ZOMATO', 'JSWSTEEL', 'TCS', 'RELIANCE', 'TATAMOTORS', 'BOSCHLTD', 'PIDILITIND', 'HINDALCO', 'INDUSINDBK', 'INDIGO', 'ABB', 'LODHA', 'SHREECEM', 'NHPC', 'BAJAJ-AUTO', 'BAJFINANCE', 'RECLTD', 'HDFCBANK', 'DRREDDY', 'POWERGRID', 'GRASIM', 'KOTAKBANK', 'TVSMOTOR', 'HEROMOTOCO', 'JINDALSTEL', 'INFY', 'BAJAJHLDNG', 'SIEMENS', 'BEL', 'SUNPHARMA'}
98

 ['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

In [44]:
import pandas as pd
analysis = pd.read_excel(r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\analysis.xlsx",header=1)
documents = pd.read_excel(r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\documents.xlsx",header=1)
prosandcons = pd.read_excel(r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\prosandcons.xlsx",header=1)
cashflow = pd.read_excel(r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\cashflow.xlsx",header=1)

In [45]:
print(analysis.columns)
print(documents.columns)
print(prosandcons.columns)

Index(['id', 'company_id', 'compounded_sales_growth',
       'compounded_profit_growth', 'stock_price_cagr', 'roe'],
      dtype='object')
Index(['id', 'company_id', 'Year', 'Annual_Report'], dtype='object')
Index(['id', 'company_id', 'pros', 'cons'], dtype='object')

In [46]:
print(analysis.duplicated().sum())
print(documents.duplicated().sum())
print(prosandcons.duplicated().sum())
print(cashflow.duplicated().sum())

0
0
0
0

In [47]:
analysis.head()

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%

In [52]:
sectors = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\supporting\sectors.xlsx",
    header=0
)

sectors.head()

,id,company_id,broad_sector,sub_sector,index_weight_pct,market_cap_category
0,1,ABB,Industrials,Capital Goods,0.81,Large Cap
1,2,ADANIENSOL,Energy,Power & Utilities,0.65,Large Cap
2,3,ADANIENT,Industrials,Conglomerates,1.50,Large Cap
3,4,ADANIGREEN,Energy,Renewable Energy,1.23,Large Cap
4,5,ADANIPORTS,Industrials,Infrastructure,2.12,Large Cap

In [53]:
stock_prices = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\supporting\stock_prices.xlsx",
    header=0
)

stock_prices.head()

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

In [56]:
financial_ratios = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\supporting\financial_ratios.xlsx",
    header=0
)

financial_ratios.head()

,id,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,earnings_per_share,book_value_per_share,dividend_payout_ratio_pct,total_debt_cr,cash_from_operations_cr
0,1,ABB,Dec 2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,68.0,3.0810,25.0,0,101.0
1,2,ABB,Mar 2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,93.0,3.7524,25.0,0,155.0
2,3,ABB,Mar 2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,93.0,3.7524,25.0,0,0.0
3,4,ABB,Mar 2015,10.00,14.0,24.44,0.0,NaN,1.6659,28.0,187.0,108.0,4.4619,29.0,0,215.0
4,5,ABB,Mar 2015,10.00,14.0,24.44,0.0,NaN,1.6659,-1899.0,1864.0,108.0,4.4619,29.0,0,-35.0

In [ ]:
df.columns = df.columns.str.strip()

print(df.columns)df.columns = df.columns.str.strip()

print(df.columns)

In [59]:
print(
    financial_ratios.duplicated(
        subset=["company_id", "year"]
    ).sum()
)

119

In [62]:
dups = financial_ratios[
    financial_ratios.duplicated(
        subset=["company_id", "year"],
        keep=False
    )
]

print(
    dups[
        ["company_id", "year"]
    ].sort_values(
        ["company_id", "year"]
    )
)

     company_id      year
1           ABB  Mar 2014
2           ABB  Mar 2014
3           ABB  Mar 2015
4           ABB  Mar 2015
5           ABB  Mar 2016
...         ...       ...
1095      TECHM  Mar 2022
1096      TECHM  Mar 2023
1097      TECHM  Mar 2023
1098      TECHM  Mar 2024
1099      TECHM  Mar 2024

[202 rows x 2 columns]

In [ ]:
pl = pd.read_excel(
    r"C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\raw\profitandloss.xlsx",
    header=1
)

print(pl.shape)

pl = pl.drop_duplicates(
    subset=["company_id", "year"]
)

print(pl.shape)

(1276, 15)
(1263, 15)

In [33]:
pl.head(2)

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0

In [38]:
pg = pd.read_excel(r'C:\Users\Prashanth Reddy\Desktop\vs code\Nifty100_Financial_Intelligence\data\supporting\peer_groups.xlsx')
pg.head()
print(pg["company_id"].duplicated().sum())

0